language: android
jdk:
  - oraclejdk8
sudo: required
addons:
  apt:
    packages:
      - oracle-java8-installer
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - tools # TODO force travis to fetch latest tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-25.0.1

    # The SDK version used to compile your project
    - android-25

    # Additional components
    - extra-android-m2repository
    # - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-19
    # - sys-img-x86-android-17
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache/
script:
    - .travis/${TASK}.sh
env:
    - TASK=lint
    - TASK=test1
    - TASK=test2
after_success:
    - .travis/coverage.sh
